version: 2
jobs: 
  build: 
   docker: 
    - image: circleci/android:api-28-ndk-r17b
   environment:
      JVM_OPTS: -Xmx3200m
   steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
